language: ruby
rvm:
  - 2.4.1
bundler_args: --jobs 1 --retry 3
dist: trusty
sudo: required
script:
  - bundle exec rails db:setup
  - bundle exec rspec
cache: bundler
services:
  - sqlite3
after_success:
  - bundle exec codeclimate-test-reporter