# config/application.yml
defaults: &defaults
  dashboard:
    aside:
      - categories
      - products
      - orders
      - users
      - settings
  product:
    statuses:
      available: available
      unavailable: unavailable
  order:
    statuses:
      pending: pending
      cancelled: cancelled
      paid: paid
      rejected: rejected
      delivered: delivered

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults