# config/application.yml
defaults: &defaults
  product:
    statuses:
      available: available
      unavailable: unavailable

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults